### ISSUE TITLE
HDInsight HBase connection string

### ISSUE THREAD

**Issue by ashishthaps** [dwdii/GarudaUtil#1]
What is going to be the connection string format for HDInsight HBase if I need  to connect to it from outside of VNET via HDInsight gateway?

**Comment by dwdii** [comment]
Hi @ashishthaps

I haven't tested with HDInsight gateway, but the underlying [Microsoft.Phoenix.Client should support it according to Nuget release notes](https://www.nuget.org/packages/Microsoft.Phoenix.Client/). 

For an HDInsight Gateway, it looks like the connection string would be like the one below based on the current Garuda.Data code:

	Server=myphoenixserver.domain.com,443;User ID=myuser;Password=mypwd;CredentialUri=http://myazurecredurl.azure.com;Request Timeout=30000

Some important points:

Server: The server itself doesn't appear to be used currently in gateway mode, but the port is relavant and needs to the port associated with your gateway.

User ID: Your gateway credential user name. 

Password: Your gateway credential password.

CredentialUri: The protocol scheme and host of the gateway

Request Timeout: The timeout in milliseconds of a given phoenix command or request to the phoenix server. I use 30000 in my tests and development.


I might have a gap with the relative path segment of the gateway uri. The way the underlying Microsoft.Phoenix.Client builds the URL, it doesn't use the complete CredentialUri, but rather uses a separate field I haven't exposed in the connection string yet. 

I'm interested in you feedback! Let me know how it goes, and I'll incorporate changes if needed.

Best Regards,

Daniel

**Comment by dwdii** [comment]
Update - I stood up an HDInsight Hbase cluster over the weekend and worked though the connection details. The ConnectionString was begging for better treatment in these cases so a new property "Mode" was added to differentiate vnet from hdi-gateway modes. The CredentialUri property is now deprecated from the ConnectionString and the Server property is used for both vnet and hdi-gateway mode. [The changes where posted to Nuget a few minutes ago in 0.5.6084.40681-beta](https://www.nuget.org/packages/Garuda.Data/0.5.6084.40681-beta). 

The ConnectionString for HDInsight would look similar to the following: 

```
Server=https://mycluster.azurehdinsight.net/hbasephoenix0/;User ID=myuser;Password=mypwd;Mode=hdi-gateway;Request Timeout=30000" 
```

I also updated the [README](https://github.com/dwdii/GarudaUtil/blob/master/README.md) for the repo to better describe the ConnectionString properties as well.

Looking forward to your feedback,

Daniel

**Comment by ashishthaps** [comment]
Thanks , this is great. Do I need to update the sample application anything else apart from connection string?
Thx, Ashish


Date: Sun, 28 Aug 2016 20:04:55 -0700

**Comment by ashishthaps** [comment]
I am able to connect but getting following error

Date: Sun, 28 Aug 2016 20:04:55 -0700

**Comment by ashishthaps** [comment]
Yes, it's working now
I had few empty tables with index. I was able to connect but with an error and could not see the list of tables. However, after droping the index things are fine.
Thx, Ashish  


Date: Sun, 28 Aug 2016 20:04:55 -0700

**Comment by dwdii** [comment]
@ashishthaps Great to hear you got it working on your side! Unfortunately the errors you mentioned did not come through to me. Did you have screenshots you could post to new github? What were the properties of the index(es) that might contribute to the error? I'm not able to reproduce an error with an empty table with an index.

**Comment by ashishthaps** [comment]
I will try doing that

I would like to highlight your work on Microsoft data lake blog , would you be ok with that?

**Comment by dwdii** [comment]
Certainly - I appreciate your interest in the project, and I hope others will find it useful also!

**Comment by dwdii** [comment]
Any follow-up comments or questions, please open a new issue. Thanks!
