### ISSUE TITLE
HDInsight 3.5

### ISSUE THREAD

**Issue by ashishthaps** [dwdii/GarudaUtil#3]
We just updated our SDK https://github.com/Azure/hdinsight-phoenix-sharp to work with Phoenix 4.7 (HDInsight 3.5) I was wondering if you can update the dependencies so that users can connect to HDInsight 3.5 Phoenix clusters as well?

**Comment by dwdii** [comment]
Thanks for raising this point @ashishthaps, I'm happy to make the upgrade. Having some scheduling issues recently though, so probably will take a bit longer. By the way, would you have an HDInsight 3.5 instance that could be used for testing?

**Comment by dwdii** [comment]
[Release v0.8.6588.36757-beta](https://github.com/dwdii/GarudaUtil/releases/tag/v0.8.6588.36757-beta) has been published though not posted to Nuget yet. This is compatible with HDInsight 3.6 and probably HDI 3.5 as well (via the Microsoft Phoenix Client 2.0 ) since they both use Phoenix 4.7.
