### ISSUE TITLE
Error 9009

### ISSUE THREAD

**Issue by towerbe** [dwdii/GarudaUtil#6]
When trying to build this solution, it immediately fails with an error.  Following is the text of the message.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "nuget pack C:\Users\TowerBE\Source\Repos\GarudaUtil\Garuda.Data\Garuda.Data.csproj -Prop Configuration=Release -Prop Platform=AnyCPU" exited with code 9009.	Garuda.Data			

I've had another person test this scenario and he is getting the same thing.  Doesn't matter if I do a release or debug build.  

I'm not a developer, so this is all foreign to me.  Any help in resolving this issue is greatly appreciated.

**Comment by towerbe** [comment]
With the help of a friend, we figured out a work around.  

Edit Garuda.Data.csproj 

Comment out the "PostBuildEvent"

 <PropertyGroup>
    
  </PropertyGroup> 

Clean the project and build again.  The error is gone (lots of warnings still exist, but the error is gone).

**Comment by dwdii** [comment]
The GarudaUtil solution automatically attempts to package the GarudaData components into a Nuget package. On the surface, your error suggests you may not have Nuget installed or at least your build environment is unable to locate the nuget.exe. See the stackoverflow post: 
https://stackoverflow.com/questions/15097538/nuget-install-exit-code-9009

Glad you were able to work around the issue for your needs. An alternative would be to solve the nuget install/pathing issues such that the build could find it. What version of Visual Studio are you using?

**Comment by towerbe** [comment]
2015 Professional

**Comment by towerbe** [comment]
I'm running Visual Studio 2015 Professional, and I do have Nuget installed (currently at version 3.5.0.1484).

**Comment by dwdii** [comment]
Yeah - per the following Nuget issue, it seems the "Nuget VSIX" which comes with VS2015 is not the same as the nuget.exe needed for packing (creating) nuget packages. Additionally, nuget.exe's containing folder needs to be added to the path for the simple nuget call to work (as in the PostBuildEvent of Garauda.Data). I vaguely remember doing this as part of my machine setup before creating Garuda.Data.

https://github.com/NuGet/Home/issues/2468#issuecomment-206588910

As you can read from the referenced Nuget issue, others have faced the same frustration you are reporting here.  Until updated by Nuget or Microsoft, I think it boils down to explicitly installing nuget and manually updating the PATH environment variable if you want to be able to run the PostBuildEvent as is.

Best regards,

Daniel
